# Generated by Django 3.1.5 on 2021-01-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
